### ISSUE TITLE
PHP Startup: Unable to load dynamic library '/usr/lib/php5/20131226/memcache.so' and '/usr/lib/php5/20131226/pthreads.so'

### ISSUE THREAD

**Issue by yswery** [gplessis/dotdeb-php5#72]
```
root@app1:~# php -v
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20131226/memcache.so' - /usr/lib/php5/20131226/memcache.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20131226/pthreads.so' - /usr/lib/php5/20131226/pthreads.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP 5.6.5-1~dotdeb.1 (cli) (built: Jan 28 2015 05:40:56)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies
```

I just upgraded a few hours ago now getting these messages...

How do I resolve this?

**Comment by gplessis** [comment]
Because of performance issues with Zend thread safety (pthreads depends on it), I had to disable it on the `wheezy-php56` repo. You now have to use the `wheezy-php56-zts` repository instead, by using this line in your sources.list :
<pre>deb http://packages.dotdeb.org wheezy-php56-zts all</pre>

Because you already did the upgrade, you might have to `apt-get install --reinstall` your php5 packages. Sorry for this change, but most users don't need pthreads, and it has a 15% impact on performance.
